name: Assemble bundle

on:
  push:
  workflow_call:

permissions:
  contents: read

jobs:
  check:
    uses: ./.github/workflows/check.yml
  bundle:
    runs-on: ubuntu-latest
    needs: [ check ]
    steps:
      - uses: actions/checkout@v3
      - name: Decode Keystore
        run: |
          echo ${{ secrets.KEY_STORE }} | base64 -di > "${RUNNER_TEMP}"/keystore.jks
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Bundle
        env:
          KEY_PATH: ${RUNNER_TEMP}/keystore.jks
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          MAPBOX_KEY: ${{ secrets.MAPBOX_KEY }}
          GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
        run: bundle exec fastlane bundle
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: app/build/outputs/**
